Repository iamparas0/TIC-TAC-TOE, pull requests merged in 2024-10, with the labels that each got.

#71 Update README.md
  README.md
Labels: documentation, enhancement, gssoc-ext, hacktoberfest-accepted, level2

#94 Updated Colors as per PR #88 and Issue #76
  paras/src/App.css
  paras/src/App.js
  paras/src/Sparkle.css
  paras/src/Sparkle.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#101 #Issue34 Patch AI mode
  package-lock.json
  paras/package-lock.json
  paras/src/App.css
  paras/src/App.js
Labels: help wanted, gssoc-ext, hacktoberfest-accepted, level3

#140 Update readme
  README.md
  package-lock.json
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#111 Implemented highest score feature for two players
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#174 made enhancements for issue #158
  paras/src/App.css
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#110 Win tracker added
  paras/src/App.css
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#189 Create auto-comment-issue.yml
  .github/workflows/auto-comment-issue.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#187 DONE ...
  paras/public/first.css
  paras/public/index.html
  paras/src/App.css
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#93 Update App.js to add a Result Board
  paras/src/App.css
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#165 Changes the color of the boxes on click
  paras/src/App.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#159 adding player name to start the game #104 issue
  paras/src/App.css
  paras/src/App.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#196 Feature branch
  paras/src/App.css
  paras/src/App.js
  paras/src/ScoreTracker.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#135 Follow us section added
  paras/public/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#259 Update Navbar and Theme Toggle Button #223
  paras/package-lock.json
  paras/package.json
  paras/public/index.html
  paras/src/App.css
  paras/src/App.js
  paras/src/ttt-icon.jpg
  paras/src/ttt-logo.svg
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#280 Add stylish CONTRIBUTING.md with guidelines, community communication, and additional resources
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level2

#400 Created voting system
  paras/public/app.js
  paras/public/index.html
  paras/public/styles.css
  paras/public/voting_system.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#356 Update favicon
  paras/public/img.png
  paras/public/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#344 Fixes:#304 - jashwanth/TicUi
  paras/src/App.css
  paras/src/App.js
  paras/src/Game.js
  paras/src/components/about .css
  paras/src/components/about.js
  paras/src/components/contact.css
  paras/src/components/contact.js
  paras/src/components/navBar.css
  paras/src/components/rules.css
  paras/src/components/rules.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#342 Updated SIgn and login Form
  paras/package-lock.json
  paras/src/Login.css
  paras/src/Signup.css
  paras/vercel.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#343 Home page navigation
  paras/vercel.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#312 added multi language translator
  paras/public/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#326 Fixed Play Against Ai Functionality
  package-lock.json
  paras/src/Game.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#384 Add an AI Chatbot in the website #258
  paras/package-lock.json
  paras/package.json
  paras/src/App.js
  paras/src/components/Chatbot/ChatContent.js
  paras/src/components/Chatbot/Chatbot.css
  paras/src/components/Chatbot/Chatbot.js
  paras/src/components/Chatbot/background.jpg
  paras/src/components/Chatbot/chatbot.gif
Labels: gssoc-ext, hacktoberfest-accepted, level3

#308 Adding Restart Button
  paras/src/App.css
  paras/src/Game.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#92 Fix Toggle Positioning and Add Win Popup in Tic Tac Toe
  package-lock.json
  package.json
  paras/package-lock.json
  paras/package.json
  paras/src/App.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#354 Tie-status updated, header alignment modified
  paras/public/first.css
  paras/src/App.css
  paras/src/Game.js
  paras/src/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#352 Dynamic Background Color Transition for Player Turns in Tic-Tac-Toe
  paras/src/Game.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#364 Added Game History Feature
  paras/src/Game.js
Labels: gssoc-ext, hacktoberfest-accepted, level2
